version: '3.9'

services:
 database:
  image: mysql
  container_name: movieDb
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: 'root'
   MYSQL_DATABASE: 'movieDb'
  ports:
   - '3306:3306'